#!/usr/bin/env python3
"""Builds THIRD-PARTY-NOTICES.txt from the real dependency graphs.

MIT, Apache-2.0, BSD, Zlib and Unicode licences all require their copyright
notice to travel with distributed binaries. Generating this rather than writing
it by hand is the only way it stays true as dependencies change.

Reads the Rust graph via `cargo metadata` and the Swift one from SwiftPM's
checkouts, then copies each package's actual licence text.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LICENSE_NAMES = ("LICENSE", "LICENCE", "COPYING", "NOTICE", "UNLICENSE")


def license_text(directory: Path) -> str:
    """The licence files a package ships, concatenated."""
    if not directory.is_dir():
        return ""

    parts = []
    for entry in sorted(directory.iterdir()):
        if not entry.is_file():
            continue
        if not entry.name.upper().startswith(LICENSE_NAMES):
            continue
        try:
            parts.append(f"--- {entry.name} ---\n{entry.read_text(encoding='utf-8', errors='replace').strip()}")
        except OSError:
            continue
    return "\n\n".join(parts)


def rust_packages(target: str) -> list[dict]:
    """Only what actually ships: the app's normal and build dependencies for one
    platform. Dev-dependencies are test-only and never distributed, and packages
    for other platforms are not linked in."""
    # Explicit pipes and bytes rather than capture_output/text: this has to run
    # identically on a Windows runner, and a silent empty stdout there is worse
    # than a loud failure.
    result = subprocess.run(
        [
            "cargo", "metadata", "--format-version", "1",
            "--filter-platform", target,
        ],
        cwd=str(ROOT / "windows"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0 or not result.stdout:
        stderr = (result.stderr or b"").decode("utf-8", errors="replace")
        sys.exit(f"cargo metadata failed (exit {result.returncode}):\n{stderr[:2000]}")

    data = json.loads(result.stdout.decode("utf-8"))

    nodes = {node["id"]: node for node in data["resolve"]["nodes"]}
    by_id = {package["id"]: package for package in data["packages"]}
    roots = [
        package["id"]
        for package in data["packages"]
        if Path(package["manifest_path"]).parent.as_posix().startswith(ROOT.as_posix())
    ]

    # Walk out from our own crates, following the kinds that end up distributed.
    shipped: set[str] = set()
    queue = list(roots)
    while queue:
        current = queue.pop()
        for dep in nodes.get(current, {}).get("deps", []):
            kinds = {d.get("kind") for d in dep.get("dep_kinds", [])}
            if kinds and kinds == {"dev"}:
                continue
            if dep["pkg"] not in shipped:
                shipped.add(dep["pkg"])
                queue.append(dep["pkg"])

    packages = []
    for package_id in shipped:
        package = by_id[package_id]
        directory = Path(package["manifest_path"]).parent
        if directory.as_posix().startswith(ROOT.as_posix()):
            continue
        packages.append(
            {
                "name": package["name"],
                "version": package["version"],
                "license": package.get("license") or "see text",
                "text": license_text(directory),
            }
        )
    return sorted(packages, key=lambda p: p["name"].lower())


def swift_packages() -> list[dict]:
    checkouts = ROOT / "macos" / ".build" / "checkouts"
    if not checkouts.is_dir():
        return []

    packages = []
    for directory in sorted(checkouts.iterdir()):
        if not directory.is_dir():
            continue
        packages.append(
            {
                "name": directory.name,
                "version": "",
                "license": "see text",
                "text": license_text(directory),
            }
        )
    return packages


def render(rust: list[dict], swift: list[dict]) -> str:
    out = [
        "THIRD-PARTY NOTICES",
        "===================",
        "",
        "Free Scribe is distributed under the MIT License; see LICENSE.",
        "",
        "It builds on the open-source packages below. Each is reproduced with the",
        "copyright notice its licence requires. Generated by scripts/generate-notices.py",
        "from the actual dependency graph, so it stays accurate as dependencies change.",
        "Dev-dependencies are excluded: they are used to test the software, not to run it.",
        "",
        "Speech recognition uses OpenAI's Whisper models (MIT). The CoreML and GGML",
        "builds are third-party conversions, downloaded at runtime rather than bundled.",
        "",
    ]

    for heading, packages in (("Rust packages", rust), ("Swift packages", swift)):
        if not packages:
            continue
        out += ["", "=" * 78, heading, "=" * 78, ""]
        for package in packages:
            label = f"{package['name']} {package['version']}".strip()
            out += ["", "-" * 78, f"{label}  ({package['license']})", "-" * 78, ""]
            out.append(package["text"] or "(no licence file shipped; see the package's repository)")

    return "\n".join(out) + "\n"


def main() -> int:
    # The macOS app is Swift with no Rust in it, and the Windows app the reverse,
    # so each bundle gets only the notices that belong to what it actually ships.
    platform = sys.argv[1] if len(sys.argv) > 1 else "windows"

    if platform == "macos":
        rust, swift = [], swift_packages()
        destinations = [ROOT / "macos" / "THIRD-PARTY-NOTICES.txt"]
        if not swift:
            print("error: no Swift checkouts — run `cd macos && swift build` first", file=sys.stderr)
            return 1
    else:
        rust, swift = rust_packages("x86_64-pc-windows-msvc"), []
        destinations = [ROOT / "windows" / "app" / "THIRD-PARTY-NOTICES.txt"]

    text = render(rust, swift)
    for destination in destinations:
        destination.write_text(text, encoding="utf-8")

    print(f"{platform}: {len(rust)} Rust, {len(swift)} Swift packages, {len(text.splitlines())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
